### PR TITLE
Fix Install-binary.sh

### PR DESCRIPTION
**Pull request by romeritoCL**
Hi! Added a fix for both ARM + Linux users

### CODE REVIEW

**Comment by romeritoCL** [comment]
Hi! this should fix both the ARM release URL issue and the --version parameter that is currently ignored.

I've done several tests on the install-binary.sh without paramters (grabs latest) and adding --version 3.1.8 (This also works)
For ARM I simply added the possible archs and inversed the order of the grep to have the linux first, since linux-arm is more restrictive. Also tested that my self setting $OS and $ARCH on the file.

This plugin is starting to be used by many people and it's good to have it working as expected 👍

**Comment by CrusaderX** [comment]
@romeritoCL 
```shell
if [VERSION='latest']; then
```

This should be fixed like `if [ $VERSION = 'latest' ]; then`

**Comment by sergeylanzman** [comment]
Any updates? today I can't install plugin

**Comment by CrusaderX** [comment]
@sergeylanzman just fork the repo and fix the issue or you can use my fork 
```shell
$ helm plugin add https://github.com/crusaderx/helm-ssm
```

**Comment by MarkAndersonTrocme** [comment]
@lolgab @pedrocodacy 

Can this get merged? Makes it  unusable for CI/CD

**Pull request closed without merging**
